# Setup
title:        Diversity at Mudd
tagline:      A centralized home for diversity resources at Harvey Mudd College
baseurl:      ''
url:          "diversity-at-mudd/"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Daniel Bashir
  url:        http://db7894.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
